// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yngtfehiiwcxgtltbtek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZ3RmZWhpaXdjeGd0bHRidGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODgwNDEsImV4cCI6MjA3NDY2NDA0MX0.f92NjmarPbjWXAux9d1E0WKFy-_9cq_srkLzXlIurts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});